package compounds

var seedCompounds = []Compound{
	{ID: "bpc_157", Name: "bpc_157", DisplayName: "BPC-157", Aliases: []string{"BPC-157", "BPC157", "BPC 157", "Body Protection Compound", "Body Protection Compound 157", "Pentadecapeptide"}, Category: CategoryHealingRecovery, Description: "Gastric pentadecapeptide with broad tissue-repair properties", Mechanism: "Upregulates growth factor expression (VEGF, FGF), promotes angiogenesis, modulates nitric oxide system", CommonRoutes: []string{"subcutaneous", "intramuscular", "oral"}, DoseUnit: "mcg"},
	{ID: "tb_500", Name: "tb_500", DisplayName: "TB-500", Aliases: []string{"TB-500", "TB500", "TB 500", "Thymosin Beta-4 Fragment", "Thymosin Beta-4", "TB4", "Tβ4"}, Category: CategoryHealingRecovery, Description: "Thymosin beta-4 fragment promoting tissue repair and cell migration", Mechanism: "Promotes cell migration and differentiation, upregulates actin, reduces inflammation", CommonRoutes: []string{"subcutaneous", "intramuscular"}, DoseUnit: "mcg"},
	{ID: "ghk_cu", Name: "ghk_cu", DisplayName: "GHK-Cu", Aliases: []string{"GHK-Cu", "GHK Cu", "GHKCu", "Copper Peptide", "GHK-Copper", "GHK Copper", "Glycyl-L-histidyl-L-lysine copper"}, Category: CategorySkinCosmetic, Description: "Copper-binding tripeptide for skin and tissue remodeling", Mechanism: "Stimulates collagen synthesis, glycosaminoglycan production, tissue remodeling, stem cell attraction", CommonRoutes: []string{"subcutaneous", "topical"}, DoseUnit: "mcg"},
	{ID: "ahk_cu", Name: "ahk_cu", DisplayName: "AHK-Cu", Aliases: []string{"AHK-Cu", "AHK Cu", "Copper Tripeptide-3", "Tripeptide-3", "Ala-His-Lys Copper"}, Category: CategorySkinCosmetic, Description: "Copper-binding tripeptide for hair growth and skin regeneration", Mechanism: "Stimulates hair follicle elongation and dermal papilla cell proliferation", CommonRoutes: []string{"topical"}, DoseUnit: "mcg"},
	{ID: "kpv", Name: "kpv", DisplayName: "KPV", Aliases: []string{"KPV", "Alpha-MSH Fragment"}, Category: CategoryGutHealth, Description: "Tripeptide from alpha-MSH C-terminal with anti-inflammatory properties", Mechanism: "Anti-inflammatory via NF-κB inhibition, antimicrobial, gut mucosal healing", CommonRoutes: []string{"oral", "subcutaneous", "topical"}, DoseUnit: "mcg"},
	{ID: "pentosan", Name: "pentosan", DisplayName: "Pentosan Polysulfate", Aliases: []string{"Pentosan", "Pentosan Polysulfate", "PPS", "Elmiron"}, Category: CategoryHealingRecovery, Description: "Semi-synthetic polysulfated xylan for joint and tissue repair", Mechanism: "GAG replenishment, anti-inflammatory, cartilage protection", CommonRoutes: []string{"subcutaneous", "intramuscular", "oral"}, DoseUnit: "mg"},
	{ID: "ll_37", Name: "ll_37", DisplayName: "LL-37", Aliases: []string{"LL-37", "LL37", "Cathelicidin"}, Category: CategoryImmune, Description: "Human cathelicidin antimicrobial peptide", Mechanism: "Direct antimicrobial activity, immune modulation, wound healing", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},

	// GH Secretagogues
	{ID: "cjc_1295_dac", Name: "cjc_1295_dac", DisplayName: "CJC-1295 DAC", Aliases: []string{"CJC-1295 DAC", "CJC-1295 with DAC", "CJC DAC", "CJC1295 DAC", "CJC 1295 DAC"}, Category: CategoryGHSecretagogue, Description: "Long-acting GHRH analog with Drug Affinity Complex", Mechanism: "GHRH analog with extended half-life via albumin binding, sustained GH elevation", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "cjc_1295_no_dac", Name: "cjc_1295_no_dac", DisplayName: "CJC-1295 (no DAC)", Aliases: []string{"CJC-1295 no DAC", "CJC-1295 without DAC", "CJC-1295", "CJC1295", "Mod GRF 1-29", "Mod GRF", "Modified GRF", "mod GRF 1-29"}, Category: CategoryGHSecretagogue, Description: "Short-acting GHRH analog preserving natural GH pulsatility", Mechanism: "GHRH analog; stimulates pulsatile GH release from pituitary", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "ipamorelin", Name: "ipamorelin", DisplayName: "Ipamorelin", Aliases: []string{"Ipamorelin", "Ipa", "Ipam", "IPA"}, Category: CategoryGHSecretagogue, Description: "Selective GH secretagogue with minimal side effects", Mechanism: "Selective ghrelin mimetic; stimulates GH release without significant cortisol/prolactin increase", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "mk_677", Name: "mk_677", DisplayName: "MK-677", Aliases: []string{"MK-677", "MK677", "MK 677", "Ibutamoren", "Nutrobal", "L-163,191"}, Category: CategoryGHSecretagogue, Description: "Oral GH secretagogue (non-peptide)", Mechanism: "Non-peptide ghrelin receptor agonist; oral bioavailability, sustained GH/IGF-1 elevation", CommonRoutes: []string{"oral"}, DoseUnit: "mg"},
	{ID: "tesamorelin", Name: "tesamorelin", DisplayName: "Tesamorelin", Aliases: []string{"Tesamorelin", "Tesa", "Egrifta"}, Category: CategoryGHSecretagogue, Description: "FDA-approved GHRH analog for lipodystrophy", Mechanism: "GHRH analog; reduces visceral adipose tissue, increases GH/IGF-1", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "sermorelin", Name: "sermorelin", DisplayName: "Sermorelin", Aliases: []string{"Sermorelin", "Serm", "Geref"}, Category: CategoryGHSecretagogue, Description: "GHRH(1-29) analog for GH stimulation", Mechanism: "GHRH analog; stimulates natural GH production and pulsatility", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "hgh", Name: "hgh", DisplayName: "HGH", Aliases: []string{"HGH", "Human Growth Hormone", "Growth Hormone", "GH", "Somatropin", "rhGH"}, Category: CategoryGHSecretagogue, Description: "Recombinant human growth hormone", Mechanism: "Direct GH replacement; stimulates IGF-1 production, promotes growth and repair", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "IU"},
	{ID: "igf_1_lr3", Name: "igf_1_lr3", DisplayName: "IGF-1 LR3", Aliases: []string{"IGF-1 LR3", "IGF-1", "IGF1 LR3", "IGF LR3", "Long R3 IGF-1"}, Category: CategoryGHSecretagogue, Description: "Long-acting insulin-like growth factor 1 analog", Mechanism: "Potent IGF-1 analog with extended half-life; promotes muscle growth and recovery", CommonRoutes: []string{"subcutaneous", "intramuscular"}, DoseUnit: "mcg"},
	{ID: "hexarelin", Name: "hexarelin", DisplayName: "Hexarelin", Aliases: []string{"Hexarelin", "Examorelin"}, Category: CategoryGHSecretagogue, Description: "Potent hexapeptide GH secretagogue", Mechanism: "Ghrelin mimetic; strong GH release, may increase cortisol/prolactin at higher doses", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "ghrp_6", Name: "ghrp_6", DisplayName: "GHRP-6", Aliases: []string{"GHRP-6", "GHRP6", "GHRP 6"}, Category: CategoryGHSecretagogue, Description: "Growth hormone releasing hexapeptide", Mechanism: "Ghrelin mimetic; stimulates appetite and GH release", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "ghrp_2", Name: "ghrp_2", DisplayName: "GHRP-2", Aliases: []string{"GHRP-2", "GHRP2", "GHRP 2"}, Category: CategoryGHSecretagogue, Description: "Growth hormone releasing peptide-2", Mechanism: "Potent ghrelin mimetic; strong GH release with less appetite stimulation than GHRP-6", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},

	// Body Composition
	{ID: "semaglutide", Name: "semaglutide", DisplayName: "Semaglutide", Aliases: []string{"Semaglutide", "Sema", "Ozempic", "Wegovy", "Rybelsus", "GLP-1"}, Category: CategoryBodyComposition, Description: "GLP-1 receptor agonist for weight management", Mechanism: "Reduces appetite via hypothalamic signaling, slows gastric emptying, improves insulin sensitivity", CommonRoutes: []string{"subcutaneous", "oral"}, DoseUnit: "mg"},
	{ID: "tirzepatide", Name: "tirzepatide", DisplayName: "Tirzepatide", Aliases: []string{"Tirzepatide", "Tirz", "Mounjaro", "Zepbound", "GIP/GLP-1"}, Category: CategoryBodyComposition, Description: "Dual GIP/GLP-1 receptor agonist", Mechanism: "Dual incretin agonist; superior weight loss vs GLP-1 alone", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "retatrutide", Name: "retatrutide", DisplayName: "Retatrutide", Aliases: []string{"Retatrutide", "Reta", "GGG agonist", "LY3437943"}, Category: CategoryBodyComposition, Description: "Triple agonist (GLP-1/GIP/Glucagon)", Mechanism: "Triple incretin agonist; targets GLP-1, GIP, and glucagon receptors", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "survodutide", Name: "survodutide", DisplayName: "Survodutide", Aliases: []string{"Survodutide", "BI 456906"}, Category: CategoryBodyComposition, Description: "Dual glucagon/GLP-1 receptor agonist", Mechanism: "Glucagon/GLP-1 agonist for weight and MASH", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "aod_9604", Name: "aod_9604", DisplayName: "AOD-9604", Aliases: []string{"AOD-9604", "AOD9604", "AOD 9604"}, Category: CategoryBodyComposition, Description: "Modified fragment of human growth hormone for fat metabolism", Mechanism: "HGH fragment (176-191); stimulates lipolysis without IGF-1 elevation", CommonRoutes: []string{"subcutaneous", "oral"}, DoseUnit: "mcg"},
	{ID: "5_amino_1mq", Name: "5_amino_1mq", DisplayName: "5-Amino-1MQ", Aliases: []string{"5-Amino-1MQ", "5-amino-1mq", "5 amino 1MQ", "NNMT inhibitor"}, Category: CategoryBodyComposition, Description: "NNMT inhibitor for fat metabolism", Mechanism: "Inhibits NNMT enzyme; increases NAD+ and SAM, promotes fat cell energy expenditure", CommonRoutes: []string{"oral"}, DoseUnit: "mg"},

	// Cognitive
	{ID: "selank", Name: "selank", DisplayName: "Selank", Aliases: []string{"Selank", "TP-7"}, Category: CategoryCognitive, Description: "Tuftsin analog with anxiolytic and nootropic properties", Mechanism: "GABA modulation, enhances BDNF expression, modulates IL-6, improves memory consolidation", CommonRoutes: []string{"nasal", "subcutaneous"}, DoseUnit: "mcg"},
	{ID: "semax", Name: "semax", DisplayName: "Semax", Aliases: []string{"Semax", "ACTH(4-7)-PGP", "Semax nasal"}, Category: CategoryCognitive, Description: "Synthetic ACTH analog with neuroprotective effects", Mechanism: "Enhances BDNF/NGF, neuroprotective, improves attention and cognitive flexibility", CommonRoutes: []string{"nasal", "subcutaneous"}, DoseUnit: "mcg"},
	{ID: "dihexa", Name: "dihexa", DisplayName: "Dihexa", Aliases: []string{"Dihexa", "N-hexanoic-Tyr-Ile-(6) aminohexanoic amide"}, Category: CategoryCognitive, Description: "Potent HGF/MET receptor system activator", Mechanism: "Hepatocyte growth factor mimetic; promotes synaptogenesis, potent nootropic in animal models", CommonRoutes: []string{"oral", "subcutaneous"}, DoseUnit: "mg"},
	{ID: "nsi_189", Name: "nsi_189", DisplayName: "NSI-189", Aliases: []string{"NSI-189", "NSI189"}, Category: CategoryCognitive, Description: "Neurogenic compound for hippocampal growth", Mechanism: "Stimulates hippocampal neurogenesis; antidepressant and procognitive effects", CommonRoutes: []string{"oral"}, DoseUnit: "mg"},

	// Anti-Aging
	{ID: "epithalon", Name: "epithalon", DisplayName: "Epithalon", Aliases: []string{"Epithalon", "Epitalon", "Epithalone", "AEDG"}, Category: CategoryAntiAging, Description: "Tetrapeptide telomerase activator", Mechanism: "Activates telomerase, regulates melatonin production, pineal gland bioregulator", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "snap_8", Name: "snap_8", DisplayName: "SNAP-8", Aliases: []string{"SNAP-8", "SNAP8", "Acetyl Octapeptide-3"}, Category: CategorySkinCosmetic, Description: "Acetyl octapeptide for wrinkle reduction", Mechanism: "Modulates SNARE complex; reduces muscle contraction depth at injection site", CommonRoutes: []string{"topical"}, DoseUnit: "mcg"},

	// Immune
	{ID: "thymosin_alpha_1", Name: "thymosin_alpha_1", DisplayName: "Thymosin Alpha-1", Aliases: []string{"Thymosin Alpha-1", "Ta1", "TA1", "Zadaxin", "Thymosin Alpha 1"}, Category: CategoryImmune, Description: "Thymic peptide for immune modulation", Mechanism: "Enhances T-cell maturation, dendritic cell activation, TLR signaling, NK cell activity", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},

	// Sexual Health
	{ID: "pt_141", Name: "pt_141", DisplayName: "PT-141", Aliases: []string{"PT-141", "PT141", "PT 141", "Bremelanotide", "Vyleesi"}, Category: CategorySexualHealth, Description: "Melanocortin receptor agonist for sexual dysfunction", Mechanism: "MC4R agonist; stimulates sexual arousal centrally via hypothalamic pathways", CommonRoutes: []string{"subcutaneous", "nasal"}, DoseUnit: "mcg"},
	{ID: "kisspeptin", Name: "kisspeptin", DisplayName: "Kisspeptin", Aliases: []string{"Kisspeptin", "Kisspeptin-10", "KP-10"}, Category: CategoryHormonal, Description: "Neuropeptide regulating reproductive hormones", Mechanism: "Stimulates GnRH release, regulates LH/FSH pulsatility", CommonRoutes: []string{"subcutaneous", "intravenous"}, DoseUnit: "mcg"},
	{ID: "gonadorelin", Name: "gonadorelin", DisplayName: "Gonadorelin", Aliases: []string{"Gonadorelin", "GnRH", "LHRH"}, Category: CategoryHormonal, Description: "Natural GnRH for fertility preservation", Mechanism: "Pulsatile administration maintains LH/FSH production during TRT", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "enclomiphene", Name: "enclomiphene", DisplayName: "Enclomiphene", Aliases: []string{"Enclomiphene", "Enclomid", "Androxal"}, Category: CategoryHormonal, Description: "Selective estrogen receptor modulator for testosterone support", Mechanism: "SERM; blocks estrogen feedback at hypothalamus, increases LH/FSH and endogenous testosterone", CommonRoutes: []string{"oral"}, DoseUnit: "mg"},

	// Tanning
	{ID: "melanotan_2", Name: "melanotan_2", DisplayName: "Melanotan II", Aliases: []string{"Melanotan II", "Melanotan 2", "MT-2", "MT2", "MT-II", "MT II"}, Category: CategoryTanning, Description: "Melanocortin receptor agonist for tanning and libido", Mechanism: "Non-selective MCR agonist; stimulates melanogenesis, may increase libido and reduce appetite", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "melanotan_1", Name: "melanotan_1", DisplayName: "Melanotan I", Aliases: []string{"Melanotan I", "Melanotan 1", "MT-1", "MT1", "Afamelanotide", "Scenesse"}, Category: CategoryTanning, Description: "Selective MC1R agonist for photoprotection", Mechanism: "Selective MC1R agonist; stimulates melanin production without broad MCR activation", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},

	// Mitochondrial / Metabolic
	{ID: "ss_31", Name: "ss_31", DisplayName: "SS-31", Aliases: []string{"SS-31", "SS31", "Elamipretide", "Bendavia", "MTP-131"}, Category: CategoryMitochondrial, Description: "Mitochondria-targeted peptide for cellular energy", Mechanism: "Targets cardiolipin in inner mitochondrial membrane; stabilizes cristae, reduces ROS", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "mots_c", Name: "mots_c", DisplayName: "MOTS-c", Aliases: []string{"MOTS-c", "MOTSc", "MOTS c"}, Category: CategoryMetabolic, Description: "Mitochondrial-derived peptide for metabolic regulation", Mechanism: "Activates AMPK, regulates metabolic homeostasis, exercise mimetic properties", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "humanin", Name: "humanin", DisplayName: "Humanin", Aliases: []string{"Humanin", "HN"}, Category: CategoryMetabolic, Description: "Mitochondrial-derived cytoprotective peptide", Mechanism: "Anti-apoptotic, neuroprotective, cardioprotective via STAT3 and IGFBP3 pathways", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},

	// Muscle
	{ID: "follistatin_344", Name: "follistatin_344", DisplayName: "Follistatin 344", Aliases: []string{"Follistatin", "Follistatin 344", "Follistatin-344", "FST344"}, Category: CategoryMuscle, Description: "Myostatin inhibitor for muscle growth", Mechanism: "Binds and neutralizes myostatin/activin; removes brake on muscle growth", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "ace_031", Name: "ace_031", DisplayName: "ACE-031", Aliases: []string{"ACE-031", "ACE031"}, Category: CategoryMuscle, Description: "Activin receptor decoy for muscle growth", Mechanism: "Soluble ActRIIB-Fc fusion; traps myostatin, activins, and GDF-11", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "peg_mgf", Name: "peg_mgf", DisplayName: "PEG-MGF", Aliases: []string{"PEG-MGF", "PEG MGF", "Pegylated Mechano Growth Factor", "IGF-1 Splice Variant"}, Category: CategoryMuscle, Description: "Pegylated mechano growth factor for muscle repair", Mechanism: "Modified IGF-1 splice variant with extended half-life; promotes muscle repair and regeneration", CommonRoutes: []string{"intramuscular", "subcutaneous"}, DoseUnit: "mcg"},

	// Cognitive (pepbase.io additions)
	{ID: "adalank", Name: "adalank", DisplayName: "Adalank", Aliases: []string{"Adalank", "N-Acetyl Selank Amidate", "NA Selank Amidate", "Enhanced Tuftsin Analog"}, Category: CategoryCognitive, Description: "Enhanced synthetic derivative of Selank with superior BBB penetration", Mechanism: "N-terminal acetylation and C-terminal amidation of Selank; anxiolytic and neuroprotective", CommonRoutes: []string{"nasal", "subcutaneous"}, DoseUnit: "mcg"},
	{ID: "adamax", Name: "adamax", DisplayName: "Adamax", Aliases: []string{"Adamax"}, Category: CategoryCognitive, Description: "Synthetic nootropic peptide derived from Semax with adamantane modification", Mechanism: "Modified Semax with enhanced stability and BBB penetration for cognitive enhancement and neuroprotection", CommonRoutes: []string{"nasal", "subcutaneous"}, DoseUnit: "mcg"},
	{ID: "cerebrolysin", Name: "cerebrolysin", DisplayName: "Cerebrolysin", Aliases: []string{"Cerebrolysin", "FPE 1070"}, Category: CategoryCognitive, Description: "Neuropeptide preparation from purified porcine brain proteins", Mechanism: "Neurotrophic support; promotes neuronal survival, synaptogenesis, and neuroplasticity", CommonRoutes: []string{"intramuscular", "intravenous"}, DoseUnit: "ml"},
	{ID: "cgp", Name: "cgp", DisplayName: "Cyclic Glycine-Proline", Aliases: []string{"cGP", "Cyclic Glycine-Proline", "Cyclic GP"}, Category: CategoryCognitive, Description: "Naturally occurring cyclic dipeptide from IGF-1 metabolism", Mechanism: "Regulates IGF-1 bioavailability; neuroprotective in Alzheimer's and Parkinson's models", CommonRoutes: []string{"oral"}, DoseUnit: "mg"},
	{ID: "na_semax_amidate", Name: "na_semax_amidate", DisplayName: "NA Semax Amidate", Aliases: []string{"NA Semax Amidate", "N-Acetyl Semax Amidate", "NASA"}, Category: CategoryCognitive, Description: "Stabilized Semax analog with enhanced cognitive effects", Mechanism: "Acetylated and amidated Semax with superior stability and bioavailability for neuroprotection", CommonRoutes: []string{"nasal"}, DoseUnit: "mcg"},
	{ID: "noopept", Name: "noopept", DisplayName: "Noopept", Aliases: []string{"Noopept", "Omberacetam", "GVS-111", "DVD-111"}, Category: CategoryCognitive, Description: "Synthetic nootropic dipeptide for cognitive enhancement", Mechanism: "Enhances BDNF and NGF expression; improves memory, learning, and concentration", CommonRoutes: []string{"oral", "nasal", "subcutaneous"}, DoseUnit: "mg"},
	{ID: "p21", Name: "p21", DisplayName: "P21", Aliases: []string{"P21", "P021", "Ac-DGGLAG-NH2"}, Category: CategoryCognitive, Description: "Tetrapeptide derived from CNTF for neurogenesis", Mechanism: "Promotes neurogenesis and cognitive function via CNTF-derived active region", CommonRoutes: []string{"nasal", "subcutaneous"}, DoseUnit: "mcg"},
	{ID: "pe_22_28", Name: "pe_22_28", DisplayName: "PE-22-28", Aliases: []string{"PE-22-28", "Mini-Spadin", "Mini Spadin"}, Category: CategoryCognitive, Description: "Heptapeptide TREK-1 antagonist with rapid antidepressant effects", Mechanism: "TREK-1 channel antagonist; enhances neurogenesis and synaptogenesis for mood improvement", CommonRoutes: []string{"nasal", "subcutaneous"}, DoseUnit: "mcg"},
	{ID: "pinealon", Name: "pinealon", DisplayName: "Pinealon", Aliases: []string{"Pinealon", "EDR", "Glu-Asp-Arg"}, Category: CategoryCognitive, Description: "Tripeptide bioregulator for cognitive and neuroprotective support", Mechanism: "Interacts with DNA to regulate gene expression for neuronal protein synthesis", CommonRoutes: []string{"oral", "nasal"}, DoseUnit: "mcg"},

	// Body Composition (pepbase.io additions)
	{ID: "adipotide", Name: "adipotide", DisplayName: "Adipotide", Aliases: []string{"Adipotide", "Prohibitin-TP01", "TP01"}, Category: CategoryBodyComposition, Description: "Peptidomimetic targeting white adipose tissue blood supply", Mechanism: "Targets prohibitin and annexin A2 on white fat; disrupts blood supply to fat cells", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "bioglutide", Name: "bioglutide", DisplayName: "Bioglutide", Aliases: []string{"Bioglutide", "NA-931"}, Category: CategoryBodyComposition, Description: "First-in-class oral quadruple receptor agonist", Mechanism: "Targets IGF-1, GLP-1, GIP, and glucagon receptors with high oral bioavailability", CommonRoutes: []string{"oral"}, DoseUnit: "mg"},
	{ID: "cagrilintide", Name: "cagrilintide", DisplayName: "Cagrilintide", Aliases: []string{"Cagrilintide", "AM833", "NN9838", "CagriSema"}, Category: CategoryBodyComposition, Description: "Synthetic amylin analog for weight management", Mechanism: "Dual amylin and calcitonin receptor agonist; reduces appetite and body weight", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "mazdutide", Name: "mazdutide", DisplayName: "Mazdutide", Aliases: []string{"Mazdutide", "IBI362", "LY3305677"}, Category: CategoryBodyComposition, Description: "Dual GLP-1/glucagon receptor agonist for weight loss", Mechanism: "Oxyntomodulin analog; dual agonist suppressing appetite and increasing energy expenditure", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "orforglipron", Name: "orforglipron", DisplayName: "Orforglipron", Aliases: []string{"Orforglipron", "LY3502970", "OWL833"}, Category: CategoryBodyComposition, Description: "Oral non-peptide GLP-1 receptor agonist", Mechanism: "Small molecule GLP-1R agonist with oral bioavailability; weight loss and glycemic control", CommonRoutes: []string{"oral"}, DoseUnit: "mg"},
	{ID: "slu_pp_332", Name: "slu_pp_332", DisplayName: "SLU-PP-332", Aliases: []string{"SLU-PP-332", "SLU PP 332"}, Category: CategoryBodyComposition, Description: "Synthetic exercise mimetic compound", Mechanism: "Pan-estrogen-related receptor agonist (ERRα focus); exercise mimetic effects without physical activity", CommonRoutes: []string{"oral"}, DoseUnit: "mg"},
	{ID: "tesofensine", Name: "tesofensine", DisplayName: "Tesofensine", Aliases: []string{"Tesofensine", "NS2330"}, Category: CategoryBodyComposition, Description: "Triple monoamine reuptake inhibitor for weight loss", Mechanism: "Inhibits reuptake of norepinephrine, dopamine, and serotonin; appetite suppression", CommonRoutes: []string{"oral"}, DoseUnit: "mg"},

	// Healing/Recovery (pepbase.io additions)
	{ID: "ara_290", Name: "ara_290", DisplayName: "Ara 290", Aliases: []string{"Ara 290", "Ara290", "Cibinetide"}, Category: CategoryHealingRecovery, Description: "Engineered erythropoietin-derived tissue-protective peptide", Mechanism: "Targets Innate Repair Receptor; tissue-protective and anti-inflammatory without erythropoietic effects", CommonRoutes: []string{"subcutaneous", "intravenous"}, DoseUnit: "mg"},
	{ID: "cartalax", Name: "cartalax", DisplayName: "Cartalax", Aliases: []string{"Cartalax", "Ala-Glu-Asp", "AED Tripeptide", "T-31"}, Category: CategoryHealingRecovery, Description: "Tripeptide bioregulator for cartilage and connective tissue", Mechanism: "Cartilage-specific bioregulator promoting joint regeneration and cellular repair", CommonRoutes: []string{"oral", "subcutaneous"}, DoseUnit: "mcg"},
	{ID: "thymosin_beta_4", Name: "thymosin_beta_4", DisplayName: "Thymosin Beta-4", Aliases: []string{"Thymosin Beta-4", "TB-4", "Tβ4", "Timbetasin", "Thymosin Beta 4"}, Category: CategoryHealingRecovery, Description: "Full-length thymosin beta-4 for tissue repair and regeneration", Mechanism: "Promotes angiogenesis, cellular migration, and wound healing; reduces inflammation", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},

	// Immune (pepbase.io additions)
	{ID: "glutathione", Name: "glutathione", DisplayName: "Glutathione", Aliases: []string{"Glutathione", "L-Glutathione", "GSH", "Reduced Glutathione"}, Category: CategoryImmune, Description: "Master antioxidant tripeptide for detoxification and immune support", Mechanism: "Neutralizes free radicals, supports detoxification pathways, enhances immune cell function", CommonRoutes: []string{"intravenous", "oral", "subcutaneous"}, DoseUnit: "mg"},
	{ID: "thymulin", Name: "thymulin", DisplayName: "Thymulin", Aliases: []string{"Thymulin", "Serum Thymic Factor", "FTS", "Facteur Thymique Serique"}, Category: CategoryImmune, Description: "Zinc-dependent thymic peptide for immune modulation", Mechanism: "Produced by thymic epithelial cells; modulates T-cell differentiation and immune function (requires zinc)", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "prostamax", Name: "prostamax", DisplayName: "Prostamax", Aliases: []string{"Prostamax", "KEDP", "Lys-Glu-Asp-Pro"}, Category: CategoryImmune, Description: "Tetrapeptide bioregulator for prostate health", Mechanism: "Tissue-specific bioregulator targeting anterior pituitary and prostate function", CommonRoutes: []string{"oral"}, DoseUnit: "mcg"},
	{ID: "vip", Name: "vip", DisplayName: "VIP", Aliases: []string{"VIP", "Vasoactive Intestinal Peptide", "Aviptadil"}, Category: CategoryImmune, Description: "Neuropeptide with anti-inflammatory and immunomodulatory properties", Mechanism: "Binds VPAC1/VPAC2 receptors; potent anti-inflammatory, vasodilatory, and neuroprotective effects", CommonRoutes: []string{"nasal", "subcutaneous", "intravenous"}, DoseUnit: "mcg"},

	// Hormonal (pepbase.io additions)
	{ID: "hcg", Name: "hcg", DisplayName: "HCG", Aliases: []string{"HCG", "hCG", "Human Chorionic Gonadotropin", "Pregnyl", "Novarel"}, Category: CategoryHormonal, Description: "Glycoprotein hormone for fertility and testosterone support", Mechanism: "LH-mimetic; stimulates Leydig cells to maintain testosterone production and testicular function", CommonRoutes: []string{"subcutaneous", "intramuscular"}, DoseUnit: "IU"},
	{ID: "oxytocin", Name: "oxytocin", DisplayName: "Oxytocin", Aliases: []string{"Oxytocin", "Pitocin", "Syntocinon"}, Category: CategoryHormonal, Description: "Neuropeptide for social bonding and reproductive function", Mechanism: "Hypothalamic peptide; promotes social bonding, trust, and reproductive functions", CommonRoutes: []string{"nasal", "subcutaneous", "intravenous"}, DoseUnit: "IU"},
	{ID: "testagen", Name: "testagen", DisplayName: "Testagen", Aliases: []string{"Testagen", "KEDG", "KEDG Tetrapeptide"}, Category: CategoryHormonal, Description: "Tetrapeptide bioregulator for pituitary and hormonal support", Mechanism: "Targets anterior pituitary; regulates TSH and supports testosterone/thyroid hormone production", CommonRoutes: []string{"oral"}, DoseUnit: "mcg"},

	// Anti-Aging (pepbase.io additions)
	{ID: "foxo4_dri", Name: "foxo4_dri", DisplayName: "FOXO4-DRI", Aliases: []string{"FOXO4-DRI", "FOXO4 DRI"}, Category: CategoryAntiAging, Description: "Senolytic peptide targeting senescent cells", Mechanism: "Disrupts FOXO4-p53 interaction; induces apoptosis in senescent cells selectively", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "nad_plus", Name: "nad_plus", DisplayName: "NAD+", Aliases: []string{"NAD+", "NAD", "Nicotinamide Adenine Dinucleotide"}, Category: CategoryAntiAging, Description: "Essential coenzyme for cellular energy and DNA repair", Mechanism: "Supports sirtuin activity, PARP-mediated DNA repair, and mitochondrial function", CommonRoutes: []string{"intravenous", "subcutaneous", "oral"}, DoseUnit: "mg"},

	// Sleep
	{ID: "dsip", Name: "dsip", DisplayName: "DSIP", Aliases: []string{"DSIP", "Delta Sleep Inducing Peptide", "Delta Sleep-Inducing Peptide"}, Category: CategorySleep, Description: "Neuropeptide for promoting deep delta wave sleep", Mechanism: "Modulates sleep-wake cycles; promotes delta wave sleep and reduces stress-related cortisol", CommonRoutes: []string{"subcutaneous", "nasal"}, DoseUnit: "mcg"},
}
