package compounds

var seedCompounds = []Compound{
	{ID: "bpc_157", Name: "bpc_157", DisplayName: "BPC-157", Aliases: []string{"BPC-157", "BPC157", "BPC 157", "Body Protection Compound", "Body Protection Compound 157", "Pentadecapeptide"}, Category: CategoryHealingRecovery, Description: "Gastric pentadecapeptide with broad tissue-repair properties", Mechanism: "Upregulates growth factor expression (VEGF, FGF), promotes angiogenesis, modulates nitric oxide system", CommonRoutes: []string{"subcutaneous", "intramuscular", "oral"}, DoseUnit: "mcg"},
	{ID: "tb_500", Name: "tb_500", DisplayName: "TB-500", Aliases: []string{"TB-500", "TB500", "TB 500", "Thymosin Beta-4 Fragment", "Thymosin Beta-4", "TB4", "Tβ4"}, Category: CategoryHealingRecovery, Description: "Thymosin beta-4 fragment promoting tissue repair and cell migration", Mechanism: "Promotes cell migration and differentiation, upregulates actin, reduces inflammation", CommonRoutes: []string{"subcutaneous", "intramuscular"}, DoseUnit: "mcg"},
	{ID: "ghk_cu", Name: "ghk_cu", DisplayName: "GHK-Cu", Aliases: []string{"GHK-Cu", "GHK Cu", "GHKCu", "Copper Peptide", "GHK-Copper", "GHK Copper"}, Category: CategorySkinCosmetic, Description: "Copper-binding tripeptide for skin and tissue remodeling", Mechanism: "Stimulates collagen synthesis, glycosaminoglycan production, tissue remodeling, stem cell attraction", CommonRoutes: []string{"subcutaneous", "topical"}, DoseUnit: "mcg"},
	{ID: "kpv", Name: "kpv", DisplayName: "KPV", Aliases: []string{"KPV", "Alpha-MSH Fragment"}, Category: CategoryGutHealth, Description: "Tripeptide from alpha-MSH C-terminal with anti-inflammatory properties", Mechanism: "Anti-inflammatory via NF-κB inhibition, antimicrobial, gut mucosal healing", CommonRoutes: []string{"oral", "subcutaneous", "topical"}, DoseUnit: "mcg"},
	{ID: "pentosan", Name: "pentosan", DisplayName: "Pentosan Polysulfate", Aliases: []string{"Pentosan", "Pentosan Polysulfate", "PPS", "Elmiron"}, Category: CategoryHealingRecovery, Description: "Semi-synthetic polysulfated xylan for joint and tissue repair", Mechanism: "GAG replenishment, anti-inflammatory, cartilage protection", CommonRoutes: []string{"subcutaneous", "intramuscular", "oral"}, DoseUnit: "mg"},
	{ID: "ll_37", Name: "ll_37", DisplayName: "LL-37", Aliases: []string{"LL-37", "LL37", "Cathelicidin"}, Category: CategoryImmune, Description: "Human cathelicidin antimicrobial peptide", Mechanism: "Direct antimicrobial activity, immune modulation, wound healing", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},

	// GH Secretagogues
	{ID: "cjc_1295_dac", Name: "cjc_1295_dac", DisplayName: "CJC-1295 DAC", Aliases: []string{"CJC-1295 DAC", "CJC-1295 with DAC", "CJC DAC", "CJC1295 DAC", "CJC 1295 DAC"}, Category: CategoryGHSecretagogue, Description: "Long-acting GHRH analog with Drug Affinity Complex", Mechanism: "GHRH analog with extended half-life via albumin binding, sustained GH elevation", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "cjc_1295_no_dac", Name: "cjc_1295_no_dac", DisplayName: "CJC-1295 (no DAC)", Aliases: []string{"CJC-1295 no DAC", "CJC-1295 without DAC", "CJC-1295", "CJC1295", "Mod GRF 1-29", "Mod GRF", "Modified GRF", "mod GRF 1-29"}, Category: CategoryGHSecretagogue, Description: "Short-acting GHRH analog preserving natural GH pulsatility", Mechanism: "GHRH analog; stimulates pulsatile GH release from pituitary", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "ipamorelin", Name: "ipamorelin", DisplayName: "Ipamorelin", Aliases: []string{"Ipamorelin", "Ipa", "Ipam", "IPA"}, Category: CategoryGHSecretagogue, Description: "Selective GH secretagogue with minimal side effects", Mechanism: "Selective ghrelin mimetic; stimulates GH release without significant cortisol/prolactin increase", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "mk_677", Name: "mk_677", DisplayName: "MK-677", Aliases: []string{"MK-677", "MK677", "MK 677", "Ibutamoren", "Nutrobal"}, Category: CategoryGHSecretagogue, Description: "Oral GH secretagogue (non-peptide)", Mechanism: "Non-peptide ghrelin receptor agonist; oral bioavailability, sustained GH/IGF-1 elevation", CommonRoutes: []string{"oral"}, DoseUnit: "mg"},
	{ID: "tesamorelin", Name: "tesamorelin", DisplayName: "Tesamorelin", Aliases: []string{"Tesamorelin", "Tesa", "Egrifta"}, Category: CategoryGHSecretagogue, Description: "FDA-approved GHRH analog for lipodystrophy", Mechanism: "GHRH analog; reduces visceral adipose tissue, increases GH/IGF-1", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "sermorelin", Name: "sermorelin", DisplayName: "Sermorelin", Aliases: []string{"Sermorelin", "Serm", "Geref"}, Category: CategoryGHSecretagogue, Description: "GHRH(1-29) analog for GH stimulation", Mechanism: "GHRH analog; stimulates natural GH production and pulsatility", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "hgh", Name: "hgh", DisplayName: "HGH", Aliases: []string{"HGH", "Human Growth Hormone", "Growth Hormone", "GH", "Somatropin", "rhGH"}, Category: CategoryGHSecretagogue, Description: "Recombinant human growth hormone", Mechanism: "Direct GH replacement; stimulates IGF-1 production, promotes growth and repair", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "IU"},
	{ID: "igf_1_lr3", Name: "igf_1_lr3", DisplayName: "IGF-1 LR3", Aliases: []string{"IGF-1 LR3", "IGF-1", "IGF1 LR3", "IGF LR3", "Long R3 IGF-1"}, Category: CategoryGHSecretagogue, Description: "Long-acting insulin-like growth factor 1 analog", Mechanism: "Potent IGF-1 analog with extended half-life; promotes muscle growth and recovery", CommonRoutes: []string{"subcutaneous", "intramuscular"}, DoseUnit: "mcg"},
	{ID: "hexarelin", Name: "hexarelin", DisplayName: "Hexarelin", Aliases: []string{"Hexarelin", "Examorelin"}, Category: CategoryGHSecretagogue, Description: "Potent hexapeptide GH secretagogue", Mechanism: "Ghrelin mimetic; strong GH release, may increase cortisol/prolactin at higher doses", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "ghrp_6", Name: "ghrp_6", DisplayName: "GHRP-6", Aliases: []string{"GHRP-6", "GHRP6", "GHRP 6"}, Category: CategoryGHSecretagogue, Description: "Growth hormone releasing hexapeptide", Mechanism: "Ghrelin mimetic; stimulates appetite and GH release", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "ghrp_2", Name: "ghrp_2", DisplayName: "GHRP-2", Aliases: []string{"GHRP-2", "GHRP2", "GHRP 2"}, Category: CategoryGHSecretagogue, Description: "Growth hormone releasing peptide-2", Mechanism: "Potent ghrelin mimetic; strong GH release with less appetite stimulation than GHRP-6", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},

	// Body Composition
	{ID: "semaglutide", Name: "semaglutide", DisplayName: "Semaglutide", Aliases: []string{"Semaglutide", "Sema", "Ozempic", "Wegovy", "Rybelsus", "GLP-1"}, Category: CategoryBodyComposition, Description: "GLP-1 receptor agonist for weight management", Mechanism: "Reduces appetite via hypothalamic signaling, slows gastric emptying, improves insulin sensitivity", CommonRoutes: []string{"subcutaneous", "oral"}, DoseUnit: "mg"},
	{ID: "tirzepatide", Name: "tirzepatide", DisplayName: "Tirzepatide", Aliases: []string{"Tirzepatide", "Tirz", "Mounjaro", "Zepbound", "GIP/GLP-1"}, Category: CategoryBodyComposition, Description: "Dual GIP/GLP-1 receptor agonist", Mechanism: "Dual incretin agonist; superior weight loss vs GLP-1 alone", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "retatrutide", Name: "retatrutide", DisplayName: "Retatrutide", Aliases: []string{"Retatrutide", "Reta", "GGG agonist", "LY3437943"}, Category: CategoryBodyComposition, Description: "Triple agonist (GLP-1/GIP/Glucagon)", Mechanism: "Triple incretin agonist; targets GLP-1, GIP, and glucagon receptors", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "survodutide", Name: "survodutide", DisplayName: "Survodutide", Aliases: []string{"Survodutide", "BI 456906"}, Category: CategoryBodyComposition, Description: "Dual glucagon/GLP-1 receptor agonist", Mechanism: "Glucagon/GLP-1 agonist for weight and MASH", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "aod_9604", Name: "aod_9604", DisplayName: "AOD-9604", Aliases: []string{"AOD-9604", "AOD9604", "AOD 9604"}, Category: CategoryBodyComposition, Description: "Modified fragment of human growth hormone for fat metabolism", Mechanism: "HGH fragment (176-191); stimulates lipolysis without IGF-1 elevation", CommonRoutes: []string{"subcutaneous", "oral"}, DoseUnit: "mcg"},
	{ID: "5_amino_1mq", Name: "5_amino_1mq", DisplayName: "5-Amino-1MQ", Aliases: []string{"5-Amino-1MQ", "5-amino-1mq", "5 amino 1MQ", "NNMT inhibitor"}, Category: CategoryBodyComposition, Description: "NNMT inhibitor for fat metabolism", Mechanism: "Inhibits NNMT enzyme; increases NAD+ and SAM, promotes fat cell energy expenditure", CommonRoutes: []string{"oral"}, DoseUnit: "mg"},

	// Cognitive
	{ID: "selank", Name: "selank", DisplayName: "Selank", Aliases: []string{"Selank", "TP-7"}, Category: CategoryCognitive, Description: "Tuftsin analog with anxiolytic and nootropic properties", Mechanism: "GABA modulation, enhances BDNF expression, modulates IL-6, improves memory consolidation", CommonRoutes: []string{"nasal", "subcutaneous"}, DoseUnit: "mcg"},
	{ID: "semax", Name: "semax", DisplayName: "Semax", Aliases: []string{"Semax", "ACTH(4-7)-PGP", "Semax nasal"}, Category: CategoryCognitive, Description: "Synthetic ACTH analog with neuroprotective effects", Mechanism: "Enhances BDNF/NGF, neuroprotective, improves attention and cognitive flexibility", CommonRoutes: []string{"nasal", "subcutaneous"}, DoseUnit: "mcg"},
	{ID: "dihexa", Name: "dihexa", DisplayName: "Dihexa", Aliases: []string{"Dihexa", "N-hexanoic-Tyr-Ile-(6) aminohexanoic amide"}, Category: CategoryCognitive, Description: "Potent HGF/MET receptor system activator", Mechanism: "Hepatocyte growth factor mimetic; promotes synaptogenesis, potent nootropic in animal models", CommonRoutes: []string{"oral", "subcutaneous"}, DoseUnit: "mg"},
	{ID: "nsi_189", Name: "nsi_189", DisplayName: "NSI-189", Aliases: []string{"NSI-189", "NSI189"}, Category: CategoryCognitive, Description: "Neurogenic compound for hippocampal growth", Mechanism: "Stimulates hippocampal neurogenesis; antidepressant and procognitive effects", CommonRoutes: []string{"oral"}, DoseUnit: "mg"},

	// Anti-Aging
	{ID: "epithalon", Name: "epithalon", DisplayName: "Epithalon", Aliases: []string{"Epithalon", "Epitalon", "Epithalone", "AEDG"}, Category: CategoryAntiAging, Description: "Tetrapeptide telomerase activator", Mechanism: "Activates telomerase, regulates melatonin production, pineal gland bioregulator", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "snap_8", Name: "snap_8", DisplayName: "SNAP-8", Aliases: []string{"SNAP-8", "SNAP8", "Acetyl Octapeptide-3"}, Category: CategorySkinCosmetic, Description: "Acetyl octapeptide for wrinkle reduction", Mechanism: "Modulates SNARE complex; reduces muscle contraction depth at injection site", CommonRoutes: []string{"topical"}, DoseUnit: "mcg"},

	// Immune
	{ID: "thymosin_alpha_1", Name: "thymosin_alpha_1", DisplayName: "Thymosin Alpha-1", Aliases: []string{"Thymosin Alpha-1", "Ta1", "TA1", "Zadaxin", "Thymosin Alpha 1"}, Category: CategoryImmune, Description: "Thymic peptide for immune modulation", Mechanism: "Enhances T-cell maturation, dendritic cell activation, TLR signaling, NK cell activity", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},

	// Sexual Health
	{ID: "pt_141", Name: "pt_141", DisplayName: "PT-141", Aliases: []string{"PT-141", "PT141", "PT 141", "Bremelanotide", "Vyleesi"}, Category: CategorySexualHealth, Description: "Melanocortin receptor agonist for sexual dysfunction", Mechanism: "MC4R agonist; stimulates sexual arousal centrally via hypothalamic pathways", CommonRoutes: []string{"subcutaneous", "nasal"}, DoseUnit: "mcg"},
	{ID: "kisspeptin", Name: "kisspeptin", DisplayName: "Kisspeptin", Aliases: []string{"Kisspeptin", "Kisspeptin-10", "KP-10"}, Category: CategoryHormonal, Description: "Neuropeptide regulating reproductive hormones", Mechanism: "Stimulates GnRH release, regulates LH/FSH pulsatility", CommonRoutes: []string{"subcutaneous", "intravenous"}, DoseUnit: "mcg"},
	{ID: "gonadorelin", Name: "gonadorelin", DisplayName: "Gonadorelin", Aliases: []string{"Gonadorelin", "GnRH", "LHRH"}, Category: CategoryHormonal, Description: "Natural GnRH for fertility preservation", Mechanism: "Pulsatile administration maintains LH/FSH production during TRT", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "enclomiphene", Name: "enclomiphene", DisplayName: "Enclomiphene", Aliases: []string{"Enclomiphene", "Enclomid", "Androxal"}, Category: CategoryHormonal, Description: "Selective estrogen receptor modulator for testosterone support", Mechanism: "SERM; blocks estrogen feedback at hypothalamus, increases LH/FSH and endogenous testosterone", CommonRoutes: []string{"oral"}, DoseUnit: "mg"},

	// Tanning
	{ID: "melanotan_2", Name: "melanotan_2", DisplayName: "Melanotan II", Aliases: []string{"Melanotan II", "Melanotan 2", "MT-2", "MT2", "MT-II", "MT II"}, Category: CategoryTanning, Description: "Melanocortin receptor agonist for tanning and libido", Mechanism: "Non-selective MCR agonist; stimulates melanogenesis, may increase libido and reduce appetite", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "melanotan_1", Name: "melanotan_1", DisplayName: "Melanotan I", Aliases: []string{"Melanotan I", "Melanotan 1", "MT-1", "MT1", "Afamelanotide", "Scenesse"}, Category: CategoryTanning, Description: "Selective MC1R agonist for photoprotection", Mechanism: "Selective MC1R agonist; stimulates melanin production without broad MCR activation", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},

	// Mitochondrial / Metabolic
	{ID: "ss_31", Name: "ss_31", DisplayName: "SS-31", Aliases: []string{"SS-31", "SS31", "Elamipretide", "Bendavia", "MTP-131"}, Category: CategoryMitochondrial, Description: "Mitochondria-targeted peptide for cellular energy", Mechanism: "Targets cardiolipin in inner mitochondrial membrane; stabilizes cristae, reduces ROS", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "mots_c", Name: "mots_c", DisplayName: "MOTS-c", Aliases: []string{"MOTS-c", "MOTSc", "MOTS c"}, Category: CategoryMetabolic, Description: "Mitochondrial-derived peptide for metabolic regulation", Mechanism: "Activates AMPK, regulates metabolic homeostasis, exercise mimetic properties", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
	{ID: "humanin", Name: "humanin", DisplayName: "Humanin", Aliases: []string{"Humanin", "HN"}, Category: CategoryMetabolic, Description: "Mitochondrial-derived cytoprotective peptide", Mechanism: "Anti-apoptotic, neuroprotective, cardioprotective via STAT3 and IGFBP3 pathways", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},

	// Muscle
	{ID: "follistatin_344", Name: "follistatin_344", DisplayName: "Follistatin 344", Aliases: []string{"Follistatin", "Follistatin 344", "Follistatin-344", "FST344"}, Category: CategoryMuscle, Description: "Myostatin inhibitor for muscle growth", Mechanism: "Binds and neutralizes myostatin/activin; removes brake on muscle growth", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mcg"},
	{ID: "ace_031", Name: "ace_031", DisplayName: "ACE-031", Aliases: []string{"ACE-031", "ACE031"}, Category: CategoryMuscle, Description: "Activin receptor decoy for muscle growth", Mechanism: "Soluble ActRIIB-Fc fusion; traps myostatin, activins, and GDF-11", CommonRoutes: []string{"subcutaneous"}, DoseUnit: "mg"},
}
